@startuml kubernetes_full

scale max 1024 width

!$PROJECT_NAME = "client_name_valtech"
!$USE_IS_PROD = %true()
!$USE_RENDERINGHOST = %false()
!$USE_APPINSIGHTS = %true()
!$INCLUDE_INFRASTRUCTURE = %true()

!includesub k8s.puml!DEFAULTS
!includesub k8s.puml!IMPORTS

!includesub k8s.puml!AZURE_COMPONENTS

Cluster_Boundary(cluster, "Kubernetes Cluster") {
    AzureKubernetesService(aksdc1, "AKS", "Azure Kubernetes") {
        KubernetesApi(KubernetesApi, "Kubernetes API", "")

        !$NS_KEY_PREFIX = "feat"
        !$IS_PROD = %false()
        Namespace_Dashed_Boundary($NS_KEY_PREFIX##_ns, "test-$PROJECT_NAME-feature1") {
            !includesub k8s.puml!NS_SECTION
        }

        !$NS_KEY_PREFIX = "develop"
        !$IS_PROD = %false()
        Namespace($NS_KEY_PREFIX##_ns, "test-$PROJECT_NAME-develop") {
            !includesub k8s.puml!NS_SECTION
        }

        !$NS_KEY_PREFIX = "test"
        !$IS_PROD = %false()
        Namespace($NS_KEY_PREFIX##_ns, "test-$PROJECT_NAME-master") {
            !includesub k8s.puml!NS_SECTION
        }

        !$NS_KEY_PREFIX = "prod"
        !$IS_PROD = %true()
        Namespace($NS_KEY_PREFIX##_ns, "prod-$PROJECT_NAME-master") {
            !includesub k8s.puml!NS_SECTION
        }
    }
}


!includesub k8s.puml!AZURE_COMPONENTS_RELATIONS

!includesub k8s.puml!INFRASTRUCTURE_PIPELINE


@enduml